### ISSUE TITLE
mblast processquery not handling sequence format handled by service

### ISSUE THREAD

**Issue by aurreco-uga** [VEuPathDB/EbrcWebSvcCommon#2]
fungi nullpointer

try using this input query below with 2 sequences; the service works and returns the combined and 2 individual results but the processquery throws a nullpointerexception

`java.lang.NullPointerException
       at java.base/java.util.regex.Matcher.getTextLength(Matcher.java:1770)
       at java.base/java.util.regex.Matcher.reset(Matcher.java:416)
       at java.base/java.util.regex.Matcher.<init>(Matcher.java:253)
       at java.base/java.util.regex.Pattern.matcher(Pattern.java:1133)
       at org.eupathdb.websvccommon.wsfplugin.blast.AbstractResultFormatter.findField(AbstractResultFormatter.java:68)
       at org.eupathdb.websvccommon.wsfplugin.blast.AbstractResultFormatter.findEvalue(AbstractResultFormatter.java:63)
       at org.eupathdb.websvccommon.wsfplugin.blast.NcbiBlastResultFormatter.processAlignment(NcbiBlastResultFormatter.java:179)
       at org.eupathdb.websvccommon.wsfplugin.blast.NcbiBlastResultFormatter.formatResult(NcbiBlastResultFormatter.java:94)
       at `

```
TTGTACAGAAAGTTAAGGAAGCCCTAGACTGGGCTCAAGCCTCCATGGCCTATTCCCAACAGAATACAGAGAATCAGGCT
AATAAACACAGGAGCCCGGCCACAAACTACCAAGTAGGAGATAAGGTCTGGCTAAGTCTGAAGAACATCCGTACGGACCA
ACCCAGTAAGAAACTTGACTGGAAGAACACCAAGTATGAGGTTATAGGCCTGGTGGGCAGTCATGCTGTACAGCTGAATA
CGCCCCCAGGGATCCATCCAGTCTTCCATGTAGACCTGCTTTGGCTGGCTTCATCAGATCCACTTCCTTCCCAGAAGAAT
>only
AATGATAGCCAGCCCCCTAGCATCATGGTGAAAAACAAATTTTTGTCTCTCAATCATGCGTTCAATTTTCCTTGCGGTGC
TGGGCCTGATGGCAACATCGTCACTTCCCAGGGTAGCCGCTCAGGAGGGCATCAGTGCTTTCGACGCCATGGCCAAGTTG
AA
```

**Comment by ryanrdoherty** [comment]
@aurreco-uga This is because there's no defline for the first sequence.  Is this a case we are supposed to support?  Seems like an invalid gff to me.  We can definitely do better than NPE, but maybe a different exception with a message like "Cannot find initial defline for sequence."   Thoughts?

**Comment by ryanrdoherty** [comment]
If there IS a defline but we can't find a specific piece of it, we log a warning and return null
```
      logger.warn("Couldn't find pattern \"" + regex + "\" in defline \""
          + defline + "\"");
      return null;
```
